name: Matrix COnfiguration

on:
  push:
  workflow_dispatch: 
    
jobs:
    deploy:
      strategy:
        fail-fast: true
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [hello-world, alpine]
          exclude:
            - images: alpine
              os: windows-latest
          include:
            - images: amd64/alpine
              os: windows-latest 
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker details
        run: docker info
        
      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}